### ISSUE TITLE
Improve UX around customization of shape and color

### ISSUE THREAD

**Issue by gallettilance** [gallettilance/kviz#7]
Should the customization be equivalent to the customization that networkx provides? if so, should the UX just be:
1. generate the graph
2. get the graph
3. modify the colors as you wish
4. set the graph using the `set` method
5. render
cc @mcxxmc

**Comment by mcxxmc** [comment]
Yes, the customization is in fact changing the settings of the elements (e.g., nodes) of the networkx.
Since the graph is first generated when a DenseGraph instance is created (see __init__() L132 self._graph = self._make_digraph()  ), it needs to take color as input. So I think it is ok to pass in customization settings at that time.
It can be changed to modify the color after getting the graph and before rendering. However, it will need to iterate through the whole graph to set the color & shape of nodes, of which the code pattern will be similar to what is in the  _make_digraph()  method. I think it will cost more time to execute the program. 
But there is a trade-off: the new UX also has advantages as it will allow users to change the colors of the graph without creating a new DenseGraph instance. Depending on how users are going to use this package, different implementations may lead to different performance. I am not sure which scenario is more likely.
Perhaps it is more user-friendly to allow them to pass in customization as inputs when creating a DenseGraph, and also gives them a way to change the customizations later (e.g., a change_customization() method that can be called before rendering)?
